name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Check project structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo "=== Client Directory ==="
        ls -la client/ || echo "No client directory"
        echo "=== Package.json ==="
        cat package.json

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install --legacy-peer-deps
        echo "Dependencies installed"

    - name: Debug build process
      run: |
        echo "=== Available scripts ==="
        npm run
        echo "=== Trying to build ==="
        npm run build || echo "Build failed, trying alternative"

    - name: Alternative build
      run: |
        echo "=== Trying direct vite build ==="
        npx vite build || echo "Vite build failed"
        echo "=== Checking for build output ==="
        find . -name "dist" -type d
        find . -name "build" -type d

    - name: Install Capacitor
      run: |
        npm install @capacitor/cli @capacitor/core @capacitor/android
        npx cap --version

    - name: Prepare for Capacitor
      run: |
        echo "=== Preparing build output ==="
        mkdir -p www
        # Copy any available build output
        cp -r client/dist/* www/ 2>/dev/null || cp -r dist/public/* www/ 2>/dev/null || echo "index.html" > www/index.html

    - name: Sync Capacitor
      run: |
        npx cap sync android

    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --info

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: chinese-typo-game-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
