name: Build Simple APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create simple web app
      run: |
        mkdir -p www
        cp simple-mobile-game.html www/index.html
        echo '{"name": "chinese-typo-game", "version": "1.0.0"}' > package.json

    - name: Install and setup Capacitor
      run: |
        npm install @capacitor/core @capacitor/cli @capacitor/android
        npx cap init "中文错字挑战" "com.typogame.app" --web-dir="www"
        
    - name: Add Android platform
      run: |
        npx cap add android

    - name: Sync Capacitor
      run: |
        npx cap sync android

    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: chinese-typo-game-simple
        path: android/app/build/outputs/apk/debug/app-debug.apk
